"""
Author: Amedeo Ceruti
Contact: amedeo.ceruti@tum.de
Date: 2022-09-02

Constants & parameters which are used throughout the datamanagement functions.
"""

from datetime import date
import collections
import string

import pandas as pd

EPSG = 25832 # 5243 or 25832 or 4326

class Parameters:
    """
    Class which containts the parameters
    """

    def __init__(self, census_path=None, iwu_path=None):
        self.cea = {
            # height of a given floor (CEA = 3, TABULA = 2.5 m, EnEV = 3.125)
            'HEIGHT_FLOOR' : 3.125,  
        # TODO integrate Geschosshöhe from TABULA data per building type
            'HEIGHT_CELLAR' : 0, # height of the cellar
            'FLOORS_CELLAR' : 0, # number of cellar floors
            # Geographic positioning system '5243' or '25832' or '4326'
            'EPSG' : EPSG,
            # id to tag all output files to store various versions
            'RUNID' : str(date.today()), 
        }
        self.zensus = {
            'RUNID' : str(date.today()), # id to tag all output files with
            'EPSG' : EPSG, 
            'HEIGHT_SURR_FILTER': 3.5,  # in m filter out buildings with less height from surroundings
            'AREA_FILTER' : 0, # m2 filter out any buildings with less area than this from cea zone
            'VOLUME_FILTER' : 250, # m3 filter out any buildings with less volume than this from cea surroundings file
            # dict w probability of being a given TABULA age category within the region
            'p_age-residential': collections.OrderedDict([('A', 0.082), ('B', 0.075), 
                ('C',0.288/3), ('D',0.288/3), ('E',0.288/3), ('F',0.309/3),
                ('G',0.309/3), ('H',0.309/3), ('I',0.152), ('J',0.095/2),
                ('K',0.095/2), ('L',0),]),
            'p_age-nonresidential': collections.OrderedDict([('A', 0.466), ('B', 0.439), ('C', 0.095)]),
            'netto_area_factor-residential': 0.84,
            'netto_area_factor-nonresidential': 0.84,
            'age_mapping-nonres': {
                'A': 'A',
                'B': 'A',
                'C': 'A',
                'D': 'A',
                'E': 'A',
                'F': 'A',
                'G': 'B',
                'H': 'B',
                'I': 'B',
                'J': 'B',
                'K': 'C',
                'L': 'C',
            },

        }
        self.typology = {'tabula_ages': (
            ('A', 1859),
            ('B', 1860),
            ('C', 1919),
            ('D', 1949),
            ('E', 1958),
            ('F', 1969),
            ('G', 1979),
            ('H', 1984),
            ('I', 1995),
            ('J', 2002),
            ('K', 2010),
            ('L', 2016),
            ),
            'iwu_ages': (
                ('A', 1978),
                ('B', 1979),
                ('C', 2010)
            ),
            # maps residential uses to CEA occupancy schedules in use_types
            'use_types': {
            'SFH': ['SINGLE_RES'],
            'TH': ['SINGLE_RES'],
            'AB': ['MULTI_RES'],
            'MFH': ['MULTI_RES'],
            'NWG_1': ['OFFICE'],
            'NWG_2': ['UNIVERSITY'],
            'NWG_3': ['HOSPITAL'],
            'NWG_7': ['RESTAURANT'],
            'NWG_G1': ['OFFICE', 'RETAIL'],
            }
        }

        if census_path is not None:
            self.set_p_age(census_path)
            self.set_p_age_iwu(census_path)

        if iwu_path is not None:
            self.set_iwu_use_type(iwu_path)
    def set_p_age(self, census_path):
        """
        Sets the p_age parameter in the zensus dictionary.

        census_path: str. Path to the census file with sum of all buildings per age category in the
        studied area. Generated by zensus_mapping.py and stored in
        data/census/zensus-processed-sum.csv
        """
        df = pd.read_csv(census_path, sep=",", header=0, index_col=0)
        self.zensus['p_age-residential'] = (df.iloc[:, 0] / df.iloc[:, 0].sum()).to_dict()
        return self.zensus['p_age-residential']

    def set_p_age_iwu(self, census_path):
        df = pd.read_csv(census_path, sep=",", header=0, index_col=0)
        self.zensus['p_age-nonresidential']['A'] = (df.loc[list(string.ascii_uppercase[:6]), :].sum() \
                                                            / df.sum()).values[0]
        self.zensus['p_age-nonresidential']['B'] = (df.loc[list(string.ascii_uppercase[6:10]), :].sum() \
                                                     / df.sum()).values[0]
        self.zensus['p_age-nonresidential']['C'] = (df.loc[['K', 'L'], :].sum() / df.sum()).values[0]
        return self.zensus['p_age-nonresidential']

    def set_iwu_use_type(self, iwu_path):
        """
        Sets the use_types parameter in the typology dictionary.

        iwu_path: str. Path to the file with the IWU building types. Generated by
        iwu_mapping.py and stored in databases/DE_type-to-IWU.csv
        """
        df = pd.read_csv(iwu_path, sep=";", header=0, index_col=0)
        
        dftype = df.set_index("iwu mapping").loc[:, ["use_type_1", "use_type_2", "use_type_3"]]
        # drop nan rows
        dftype = dftype.dropna(how='all')
        # drop duplicated rows
        dftype2 = dftype[~dftype.duplicated(keep='first')]

        # check if there are any with the same index differing from each other
        if len(dftype2) != len(dftype.index.unique()):
            raise ValueError('There are duplicate entries in the IWU mapping file for use types.')
        # convert to dict and store in variable lengths lists for each key depemnding on columns
        # without nan
        d = {}
        for key, value in dftype2.iterrows():
            d[key] = [i for i in value.values if isinstance(i, str)]
        # overwrite the typology dictionary, adding new use types if necessary and modifying the
        # existing ones without deleting the initialized ones.
        self.typology['use_types'].update(d)

        return self.typology['use_types']